### ISSUE TITLE
Guide to creating gifs for published package README.

### ISSUE THREAD

**Issue by jbranchaud** [jbranchaud/splitting-atoms#32]
Pretty much all packages for Atom should have a gif showing off the functionality. Could someone write up a guide explaining what tool to use and the process for doing this?

In a recent tweet, @mojombo recommended [licecap](http://www.cockos.com/licecap/) as a good tool for Mac and Windows.

**Comment by rgbkrk** [comment]
Licecap is legit. I tried using ffmpeg+gifsicle, which looked _really_ ugly. Licecap is a breeze though.

I can take a quick stab. Where would you like it, organizationally?

**Comment by kenwheeler** [comment]
So awesome. I was wondering how they did this.

**Comment by rgbkrk** [comment]
Yes, for once I'm a `they`!

![beautify](https://f.cloud.github.com/assets/836375/2339945/50a2873a-a4bc-11e3-9cba-96e3cf7d1952.gif)

**Comment by kenwheeler** [comment]
@rgbkrk my office memes are going to be amazing because of this

**Comment by kenwheeler** [comment]
Seriously, its amazing

https://atom.io/packages/task-list

**Comment by rgbkrk** [comment]
Now how do I record licecap with licecap so there's an animated gif?

**Comment by kenwheeler** [comment]
You might break the space time continuum doing stuff like that

**Comment by rgbkrk** [comment]
Apparently it can be done!

![whatever](https://f.cloud.github.com/assets/836375/2340663/d6bdd86e-a4c7-11e3-9dc3-74e2371e02ef.gif)

And now for my final trick...

![licecapincap](https://f.cloud.github.com/assets/836375/2340667/e6c73746-a4c7-11e3-8e6f-4252f371230e.gif)

**Comment by jbranchaud** [comment]
My mind just blew up!

As for the guide, I think it can probably go in its own markdown file in the top level directory for now. Seems general enough for that.

**Comment by rgbkrk** [comment]
Just had to invoke another in a separate terminal. :wink:

```
$ /Applications/LICEcap.app/Contents/MacOS/licecap
```

**Comment by ghost** [comment]
Interesting read: http://www.sublimetext.com/~jps/animated_gifs_the_hard_way.html

**Comment by ghost** [comment]
Camtasia Studio can output a gif for those who have it installed.
