### ISSUE TITLE
Consider changing the file and directory naming scheme

### ISSUE THREAD

**Issue by tombell** [jbranchaud/splitting-atoms#44]
Visually it's hard for someone browsing the repository to parse the camel cased file and directory names. I would consider something using hyphens or underscores to separate the words.

For example:
- `CustomizingAtomWithInit.md` to `customising_atom_with_init.md` or `Customising-Atom-With-Init.md`

I feel it's a lot easier to read at a glance if you're looking for something, especially with some of the longer names.

**Comment by jbranchaud** [comment]
Thanks for the recommendation. I agree.

I personally prefer the hyphens. I will make a note somewhere (`README.md` or `CONTRIBUTING.md`) that suggests such a naming convention going forward.
