### ISSUE TITLE
Focus README content on information about the repository

### ISSUE THREAD

**Issue by jbranchaud** [jbranchaud/splitting-atoms#50]
Right now the `README` is a mix of information about this repository (repo description, how to contribute, license information) and Splitting Atoms content (installing packages, etc.). I think the `README` should focus on the former, repository information. The Splitting Atoms content can be moved to appropriate documents that get built as part of the site.

The `README` should then also address Jekyll project dependencies, how to get your local environment setup for working with this project, and how to serve the site locally. Anything else?

With respect to serving the site locally, it should be noted that you need to run it with `jekyll serve --watch --baseurl=`.

**Comment by ZucchiniZe** [comment]
Nothing that I can think of, have you looked at [this](https://github.com/jbranchaud/splitting-atoms/pull/47)?

**Comment by jbranchaud** [comment]
Fixed in #71.
