### ISSUE TITLE
Adding Icons

### ISSUE THREAD

**Issue by ZucchiniZe** [jbranchaud/splitting-atoms#64]
I think we need to add a real favicon plus a real logo.
## Here are some resources

[favicon](https://atom.io/favicon.ico)
[logo base](http://og.github.com/atom-mark/atom-mark@1200x630.png)

**Comment by DWiechert** [comment]
Do you know the licenses on those icons? We don't want to be using them if they're copyrighted.

**Comment by jbranchaud** [comment]
I agree we need a real icon, but I would like to use something that is under creative commons (or similarly permissive) and preferably custom for Splitting Atoms. I am hesitant to use Atom's icon because that isn't our brand, plus this guide isn't affiliated with it.

**Comment by jbranchaud** [comment]
Closing, duplicate of #51.
